version: "3"
services:
  postgres:
    image: postgres:10.11
    environment:
      POSTGRES_DB: bank_encripted_db_name
      POSTGRES_USER: encripted_user
      POSTGRES_PASSWORD: encripted_password
    ports:
      - "6432:5432"
  bank:
    image: bank:0.0.1
    environment:
      BANK_DATABASE_NAME: bank_encripted_db_name
      BANK_DATABASE_USER: encripted_user
      BANK_DATABASE_PASSWORD: encripted_password
      BANK_DATABASE_HOST: postgres
      BANK_DATABASE_PORT: 5432
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "8443:8443"
    deploy:
      mode: replicated
      replicas: 1
  nginx:
    image: nginx:latest
    volumes:
      - ./../configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bank
    ports:
      - "80:80"