// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: payments.proto

package payments

import (
	"context"
	"testing"

	desc "github.com/maratkanov-a/bank/pkg/payments"
	"github.com/stretchr/testify/require"
)

func TestImplementation_Create(t *testing.T) {
	api := NewPayments()
	_, err := api.Create(context.Background(), &desc.CreateRequest{})

	require.NotNil(t, err)
	require.Equal(t, "Create not implemented", err.Error())
}
