// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: payments.proto

package payments

import (
	"context"
	"github.com/sirupsen/logrus"

	desc "github.com/maratkanov-a/bank/pkg/payments"
)

func (i *Implementation) Get(ctx context.Context, req *desc.GetRequest) (*desc.GetResponse, error) {
	if err := req.Validate(); err != nil {
		logrus.Error(err)
		return nil, err
	}

	payment, err := i.pr.GetByIDMock(ctx, req.ID)
	if err != nil {
		logrus.Error(err)
		return nil, err
	}

	convertedP, err := convertToProto(payment)
	if err != nil {
		logrus.Error(err)
		return nil, err
	}

	return &desc.GetResponse{Payment: convertedP}, nil
}
