// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: payments.proto

package payments

import (
	"context"

	desc "github.com/maratkanov-a/bank/pkg/payments"
	"github.com/pkg/errors"
)

func (i *Implementation) Get(ctx context.Context, req *desc.GetRequest) (*desc.GetResponse, error) {
	return nil, errors.New("Get not implemented")
}
