// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: payments.proto

package payments

import (
	"context"
	"github.com/sirupsen/logrus"

	desc "github.com/maratkanov-a/bank/pkg/payments"
)

func (i *Implementation) List(ctx context.Context, req *desc.ListRequest) (*desc.ListResponse, error) {
	if err := req.Validate(); err != nil {
		logrus.Error(err)
		return nil, err
	}

	payments, err := i.pr.List(ctx)
	if err != nil {
		logrus.Error(err)
		return nil, err
	}

	return &desc.ListResponse{Payments: convertToProtos(payments)}, nil
}
