// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: payments.proto

package payments

import (
	desc "github.com/maratkanov-a/bank/pkg/payments"
	"github.com/utrack/clay/v2/transport"
)

type Implementation struct{}

// NewPayments create new Implementation
func NewPayments() *Implementation {
	return &Implementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewPaymentsServiceDesc(i)
}
