// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: accounts.proto

package accounts

import (
	"context"

	desc "github.com/maratkanov-a/bank/pkg/accounts"
	"github.com/pkg/errors"
)

func (i *Implementation) Create(ctx context.Context, req *desc.CreateRequest) (*desc.CreateResponse, error) {
	return nil, errors.New("Create not implemented")
}
