// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: accounts.proto

package accounts

import (
	"context"
	"github.com/sirupsen/logrus"

	desc "github.com/maratkanov-a/bank/pkg/accounts"
)

func (i *Implementation) Delete(ctx context.Context, req *desc.DeleteRequest) (*desc.DeleteResponse, error) {
	if err := req.Validate(); err != nil {
		logrus.Error(err)
		return nil, err
	}

	err := i.ar.Delete(ctx, req.ID)
	if err != nil {
		logrus.Error(err)
		return nil, err
	}

	return &desc.DeleteResponse{}, nil
}
